### ISSUE TITLE
How can I make the image take up more space on screen?

### ISSUE THREAD

**Issue by jrdn91** [mrchimp/imagelightbox#4]
I'm trying to figure out how to make the image take up more screen width than it currently does.

On certain break points I've moved the arrows to the bottom of the screen and now I want the actual image to take up more width than it does now.

How would I go about getting the script to set the width to be bigger?

**Comment by mrchimp** [comment]
I don't have time to look into it deeply at the moment but check out the setImage function around line 83, I think that should get you started. There's currently no way to do change this in the options.

**Comment by jrdn91** [comment]
Ah cool that will work for this instance. Thanks.
