### ISSUE TITLE
JS error when linked from no-image

### ISSUE THREAD

**Issue by d0ublezer0** [mrchimp/imagelightbox#6]
If link to popup image is not attached to IMG tag you will got error, because <A> tag dont have [ALT] attribute:

<a href="/cert.jpg" data-imagelightbox="f">Certificate</a>

Solution is: check "description" variable, before using them:
captionOn = function () {
        var description = $('a[href="' + $('#imagelightbox').attr('src') + '"] img').attr('alt');
        if (description){
        if (description.length > 0)
            $('<div id="imagelightbox-caption">' + description + '</div>').appendTo('body');
        }
    }

**Comment by mrchimp** [comment]
Hello. I am no longer developing this project. There is a much more active and generally better version of it [here](https://github.com/rejas/imagelightbox). You should use that instead.
